version: "3"

services:
  dashboard:
    build: .
    container_name: dashboard-financeiro
    restart: always
    expose:
      - 8501
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLEXSENDFILE=false
    networks:
      - rede_dashboard

  nginx:
    image: nginx:latest
    container_name: nginx-financeiro
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard
    networks:
      - rede_dashboard

networks:
  rede_dashboard:
    driver: bridge
